# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(804, 649)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(410, 590, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBoxBitControll = QtWidgets.QGroupBox(Dialog)
        self.groupBoxBitControll.setGeometry(QtCore.QRect(440, 360, 231, 181))
        self.groupBoxBitControll.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBoxBitControll)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 221, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelBitControllMethod = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelBitControllMethod.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.labelBitControllMethod)
        self.comboBoxBitControllMethod = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxBitControllMethod.setObjectName("comboBox")
        self.comboBoxBitControllMethod.addItem("")
        self.comboBoxBitControllMethod.addItem("")
        self.comboBoxBitControllMethod.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBoxBitControllMethod)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelCRF = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelCRF.setObjectName("label")
        self.horizontalLayout.addWidget(self.labelCRF)
        self.spinBoxCRF = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxCRF.setObjectName("spinBox")
        self.spinBoxCRF.setRange(1, 51)
        self.spinBoxCRF.setSingleStep(1)
        self.horizontalLayout.addWidget(self.spinBoxCRF)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelQP = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelQP.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.labelQP)
        self.spinBoxQP = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxQP.setObjectName("spinBox_2")
        self.spinBoxQP.setRange(1, 51)
        self.spinBoxQP.setSingleStep(1)
        self.horizontalLayout_2.addWidget(self.spinBoxQP)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelBitRate = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelBitRate.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.labelBitRate)
        self.spinBoxBitRate = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxBitRate.setObjectName("spinBox_3")
        self.spinBoxBitRate.setRange(1, 5000)
        self.spinBoxBitRate.setSuffix('k')
        self.spinBoxBitRate.setSingleStep(1)
        self.horizontalLayout_3.addWidget(self.spinBoxBitRate)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBoxVideoSourceSetting = QtWidgets.QGroupBox(Dialog)
        self.groupBoxVideoSourceSetting.setGeometry(QtCore.QRect(90, 110, 251, 181))
        self.groupBoxVideoSourceSetting.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBoxVideoSourceSetting)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 30, 191, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelFrameRate = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelFrameRate.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.labelFrameRate)
        self.spinBoxFrameRate = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBoxFrameRate.setObjectName("lineEdit_4")
        self.spinBoxFrameRate.setRange(16, 50)
        self.spinBoxFrameRate.setSingleStep(1)
        self.horizontalLayout_5.addWidget(self.spinBoxFrameRate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelPreset = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelPreset.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.labelPreset)
        self.comboBoxPreset = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBoxPreset.setObjectName("comboBoxPreset")
        self.comboBoxPreset.addItem("")
        self.comboBoxPreset.addItem("")
        self.comboBoxPreset.addItem("")
        self.comboBoxPreset.addItem("")
        self.comboBoxPreset.addItem("")
        self.comboBoxPreset.addItem("")
        self.comboBoxPreset.addItem("")
        self.comboBoxPreset.addItem("")
        self.comboBoxPreset.addItem("")
        self.comboBoxPreset.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBoxPreset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelTune = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelTune.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.labelTune)
        self.comboBoxTune = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBoxTune.setObjectName("comboBoxTune")
        self.comboBoxTune.addItem("")
        self.comboBoxTune.addItem("")
        self.comboBoxTune.addItem("")
        self.comboBoxTune.addItem("")
        self.comboBoxTune.addItem("")
        self.comboBoxTune.addItem("")
        self.comboBoxTune.addItem("")
        self.comboBoxTune.addItem("")
        self.comboBoxTune.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBoxTune)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.groupBoxFrameSetting = QtWidgets.QGroupBox(Dialog)
        self.groupBoxFrameSetting.setGeometry(QtCore.QRect(440, 60, 271, 271))
        self.groupBoxFrameSetting.setObjectName("groupBox_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBoxFrameSetting)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 30, 221, 211))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelIDRMax = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.labelIDRMax.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.labelIDRMax)
        self.spinBoxIDRMax = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBoxIDRMax.setObjectName("spinBoxIDRMax")
        self.spinBoxIDRMax.setRange(150, 500)
        self.spinBoxIDRMax.setSingleStep(10)
        self.horizontalLayout_8.addWidget(self.spinBoxIDRMax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelIDRMin = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.labelIDRMin.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.labelIDRMin)
        self.spinBoxIDRMin = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBoxIDRMin.setObjectName("spinBoxIDRMin")
        self.spinBoxIDRMin.setRange(1, 99)
        self.spinBoxIDRMin.setSingleStep(10)
        self.horizontalLayout_9.addWidget(self.spinBoxIDRMin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelRefFrame = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.labelRefFrame.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.labelRefFrame)
        self.spinBoxRefFrame = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBoxRefFrame.setObjectName("spinBoxRefFrame")
        self.spinBoxRefFrame.setRange(1, 30)
        self.spinBoxRefFrame.setSingleStep(1)
        self.horizontalLayout_10.addWidget(self.spinBoxRefFrame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelSceneCut = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.labelSceneCut.setObjectName("labelSceneCut")
        self.horizontalLayout_11.addWidget(self.labelSceneCut)
        self.spinBoxSceneCut = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBoxSceneCut.setObjectName("spinBoxSceneCut")
        self.spinBoxSceneCut.setSingleStep(1)
        self.spinBoxSceneCut.setRange(0, 100)
        self.horizontalLayout_11.addWidget(self.spinBoxSceneCut)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelBFrame = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.labelBFrame.setObjectName("labelBFrame")
        self.horizontalLayout_12.addWidget(self.labelBFrame)
        self.spinBoxBFrame = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBoxBFrame.setObjectName("spinBoxBFrame")
        self.spinBoxBFrame.setRange(0, 20)
        self.spinBoxBFrame.setSingleStep(1)
        self.horizontalLayout_12.addWidget(self.spinBoxBFrame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labelBAdapt = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.labelBAdapt.setObjectName("labelBAdapt")
        self.horizontalLayout_13.addWidget(self.labelBAdapt)
        self.comboBoxBAdapt = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBoxBAdapt.setObjectName("comboBoxBAdapt")
        self.comboBoxBAdapt.addItem("")
        self.comboBoxBAdapt.addItem("")
        self.comboBoxBAdapt.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBoxBAdapt)
        # self.lineEdit_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        # self.lineEdit_10.setObjectName("lineEdit_10")
        # self.horizontalLayout_13.addWidget(self.lineEdit_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(100, 340, 261, 211))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(40, 40, 201, 141))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.labelDeblock = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.labelDeblock.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.labelDeblock)
        self.comboBoxDeblock = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBoxDeblock.setObjectName("comboBoxDeblock")
        self.comboBoxDeblock.addItem("")
        self.comboBoxDeblock.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBoxDeblock)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.labelDeblockAlpha = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.labelDeblockAlpha.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.labelDeblockAlpha)
        self.spinBoxDeblockAlpha = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.spinBoxDeblockAlpha.setObjectName("lineEdit_11")
        self.spinBoxDeblockAlpha.setRange(-6, 6)
        self.spinBoxDeblockAlpha.setSingleStep(1)
        self.horizontalLayout_14.addWidget(self.spinBoxDeblockAlpha)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.labelDeblockBeta = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.labelDeblockBeta.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.labelDeblockBeta)
        self.spinBoxDeblockBeta = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.spinBoxDeblockBeta.setObjectName("lineEdit_12")
        self.spinBoxDeblockBeta.setRange(-6, 6)
        self.spinBoxDeblockBeta.setSingleStep(1)
        self.horizontalLayout_15.addWidget(self.spinBoxDeblockBeta)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBoxBitControll.setTitle(_translate("Dialog", "码率控制"))
        self.labelBitControllMethod.setText(_translate("Dialog", "码控方式"))
        self.comboBoxBitControllMethod.setItemText(0, _translate("Dialog", "恒定质量"))
        self.comboBoxBitControllMethod.setItemText(1, _translate("Dialog", "恒定量化"))
        self.comboBoxBitControllMethod.setItemText(2, _translate("Dialog", "恒定码率"))
        self.labelCRF.setText(_translate("Dialog", "固定质量值"))
        self.labelQP.setText(_translate("Dialog", "固定量化值"))
        self.labelBitRate.setText(_translate("Dialog", "平均码率"))
        self.groupBoxVideoSourceSetting.setTitle(_translate("Dialog", "视频源设置"))
        self.labelFrameRate.setText(_translate("Dialog", "帧速率"))
        self.labelPreset.setText(_translate("Dialog", "编码速率"))
        self.comboBoxPreset.setItemText(0, _translate("Dialog", "default"))
        self.comboBoxPreset.setItemText(1, _translate("Dialog", "ultrafast"))
        self.comboBoxPreset.setItemText(2, _translate("Dialog", "superfast"))
        self.comboBoxPreset.setItemText(3, _translate("Dialog", "veryfast"))
        self.comboBoxPreset.setItemText(4, _translate("Dialog", "fast"))
        self.comboBoxPreset.setItemText(5, _translate("Dialog", "medium"))
        self.comboBoxPreset.setItemText(6, _translate("Dialog", "slow"))
        self.comboBoxPreset.setItemText(7, _translate("Dialog", "slower"))
        self.comboBoxPreset.setItemText(8, _translate("Dialog", "veryslow"))
        self.comboBoxPreset.setItemText(9, _translate("Dialog", "placebo"))
        self.labelTune.setText(_translate("Dialog", "视频源"))
        self.comboBoxTune.setItemText(0, _translate("Dialog", "default"))
        self.comboBoxTune.setItemText(1, _translate("Dialog", "film"))
        self.comboBoxTune.setItemText(2, _translate("Dialog", "animation"))
        self.comboBoxTune.setItemText(3, _translate("Dialog", "grain"))
        self.comboBoxTune.setItemText(4, _translate("Dialog", "stillimage"))
        self.comboBoxTune.setItemText(5, _translate("Dialog", "psnr"))
        self.comboBoxTune.setItemText(6, _translate("Dialog", "ssim"))
        self.comboBoxTune.setItemText(7, _translate("Dialog", "fastdecode"))
        self.comboBoxTune.setItemText(8, _translate("Dialog", "zerolatency"))
        self.groupBoxFrameSetting.setTitle(_translate("Dialog", "帧设置"))
        self.labelIDRMax.setText(_translate("Dialog", "最大IDR帧间隔"))
        self.labelIDRMin.setText(_translate("Dialog", "最小IDR帧间隔"))
        self.labelRefFrame.setText(_translate("Dialog", "最大参考帧数"))
        self.labelSceneCut.setText(_translate("Dialog", "场景切换门限"))
        self.labelBFrame.setText(_translate("Dialog", "最大B帧数量"))
        self.labelBAdapt.setText(_translate("Dialog", "自适应B帧策略"))
        self.groupBox_4.setTitle(_translate("Dialog", "滤波器设置"))
        self.labelDeblock.setText(_translate("Dialog", "去块滤波器"))
        self.comboBoxDeblock.setItemText(0, _translate("Dialog", "不启动"))
        self.comboBoxDeblock.setItemText(1, _translate("Dialog", "启动"))
        self.labelDeblockAlpha.setText(_translate("Dialog", "alpha滤波器"))
        self.labelDeblockBeta.setText(_translate("Dialog", "beta滤波器"))
        self.comboBoxBAdapt.setItemText(0, _translate("Dialog", "关闭"))
        self.comboBoxBAdapt.setItemText(1, _translate("Dialog", "快速"))
        self.comboBoxBAdapt.setItemText(2, _translate("Dialog", "最优"))

